### ISSUE TITLE
Used-defined aspects

### ISSUE THREAD

**Issue by 0xF6** [vein-lang/vein#17]
* [x] Proposed
* [x] Triage: Completed
* [x] Prototype: in process
* [x] Implementation: not started
* [ ] Specification: not started

## define custom aspect
```csharp
public aspect customAspect(arg1: String, arg2: String);

[customAspect("foo", "bar")]
public fn(): void {}
```

## std api for reflection of custom aspect
```csharp
[customAspect("foo", "bar")]
public FooMethod(): void 
{
    auto aspect = getType(this)
              .getMethod(nameof(FooMethod))
              .getAspects()
              .first()
              .as<customAspect>();
    
    Out.println(aspect.arg1); // "foo"
    Out.println(aspect.arg2); // "bar"
}
```

### Ishtar view (transformation result)

```csharp
[aspect]
public class customAspect: mana/lang/RuntimeAspect
{
    public new(arg1: String, arg2: String): this
    { 
        // ...
    }
}

**Comment by urumo** [comment]
Hi, we need this feature ASAP, can you please prioritize it?

**Comment by 0xF6** [comment]
> Hi, we need this feature ASAP, can you please prioritize it?

no :)
there are more important tasks~

**Comment by 0xF6** [comment]
> Hi, we need this feature ASAP, can you please prioritize it?

That is resolved, try use :)

**Comment by 0xF6** [comment]
> Hi, we need this feature ASAP, can you please prioritize it?

@urumo That is resolved, try use :)

**Comment by urumo** [comment]
@0xF6 thanks for notifying, but too much time has passed since we began to feel the need in this feature, so we decided to rewrite our software using golang
