### ISSUE TITLE
Road to 0.30 release 

### ISSUE THREAD

**Issue by 0xF6** [vein-lang/vein#258]
- [x] rework readme.md
- [x] additional pages for docs
- [x] finalization install scripts
- [x] update libraries in package registry
- [x] ~~first support await operation~~
- [x] finalization network api in std
- [x] rename veinc to vein (cli moment)
- [x] ~~update libuv to next major~~
- [x] workload packages
- [x] ~~enable basis lsp functions in extension~~
- [x] ini config support
- [x] migrate last classes to structs and unsafe
- [x] rune cli do not include compiler (use ipc)
