### ISSUE TITLE
Package implementation for http using libhttp

### ISSUE THREAD

**Issue by 0xF6** [vein-lang/vein#260]
- [x] fork libhttp to vein org
- [ ] setup CI\CD for windows-x64, windows-arm64 (optional), linux-x64, linux-arm64, osx-x64, osx-arm64
- [ ] create shard package with bindings
- [ ] test for package
